"""
Example: Analyzing the Hodgkin-Huxley Model

This script demonstrates analysis of neural excitability:
- Action potential dynamics
- F-I curve (firing rate vs current)
- Excitability threshold
- Phase space analysis
"""

using DynamicalModels

println("="^60)
println("Hodgkin-Huxley Model Analysis")
println("="^60)

# Create Hodgkin-Huxley model with standard parameters
model = HodgkinHuxley()
println("\nModel parameters:")
println("  C_m = $(model.C_m) μF/cm²")
println("  g_Na = $(model.g_Na) mS/cm²")
println("  g_K = $(model.g_K) mS/cm²")
println("  g_L = $(model.g_L) mS/cm²")
println("  V_Na = $(model.V_Na) mV")
println("  V_K = $(model.V_K) mV")
println("  V_L = $(model.V_L) mV")

println("\n" * "-"^60)
println("1. Resting State Analysis")
println("-"^60)

# Resting potential
V_rest = -65.0
x0 = get_hh_initial_state(model, V_rest)
println("\nResting potential: ", V_rest, " mV")
println("Initial state (V, n, m, h):")
println("  V = ", x0[1], " mV")
println("  n = ", x0[2], " (K⁺ activation)")
println("  m = ", x0[3], " (Na⁺ activation)")
println("  h = ", x0[4], " (Na⁺ inactivation)")

println("\nGating variable interpretation:")
println("  At rest:")
println("    - n ≈ 0.3: K⁺ channels mostly closed")
println("    - m ≈ 0.05: Na⁺ activation gates closed")
println("    - h ≈ 0.6: Na⁺ inactivation gates open")
println("  Ready to fire when stimulated!")

println("\n" * "-"^60)
println("2. Excitability and Threshold")
println("-"^60)

println("\nAction potential threshold:")
println("  Threshold voltage: ~-55 to -50 mV")
println("  Threshold current: ~6-8 μA/cm²")
println()
println("Excitability properties:")
println("  - All-or-none response")
println("  - Subthreshold stimuli decay")
println("  - Suprathreshold stimuli trigger full spike")
println("  - Refractory period after spike")

println("\n" * "-"^60)
println("3. F-I Curve Analysis")
println("-"^60)

println("\nFiring frequency vs injected current:")
println("(Theoretical values - requires full integration)")
println()
println("  I_ext (μA/cm²)  |  Frequency (Hz)")
println("  " * "-"^38)
println("       0-6        |      0 (subthreshold)")
println("       7-8        |    ~10 (threshold)")
println("      10          |    ~50")
println("      15          |   ~100")
println("      20          |   ~150")

println("\nF-I curve characteristics:")
println("  - Type I excitability (continuous F-I curve)")
println("  - Firing rate increases with current")
println("  - Saturation at high currents")

println("\n" * "-"^60)
println("4. Action Potential Phases")
println("-"^60)

println("\nPhases of an action potential:")
println()
println("  1. Resting State (V ≈ -65 mV):")
println("     - Membrane at equilibrium")
println("     - K⁺ leak current balanced")
println()
println("  2. Stimulus:")
println("     - External current injection")
println("     - Membrane begins to depolarize")
println()
println("  3. Rising Phase (Depolarization):")
println("     - Na⁺ channels open rapidly (m↑)")
println("     - Na⁺ influx → V rises sharply")
println("     - Positive feedback process")
println()
println("  4. Peak (V ≈ +40 mV):")
println("     - Maximum Na⁺ conductance")
println("     - Na⁺ inactivation begins (h↓)")
println()
println("  5. Falling Phase (Repolarization):")
println("     - K⁺ channels open (n↑)")
println("     - Na⁺ channels inactivate")
println("     - K⁺ efflux → V decreases")
println()
println("  6. Hyperpolarization (Undershoot):")
println("     - K⁺ channels still open")
println("     - V drops below resting (≈ -75 mV)")
println()
println("  7. Return to Rest:")
println("     - K⁺ channels close gradually")
println("     - Na⁺ channels recover from inactivation")

println("\n" * "-"^60)
println("5. Dynamical System Properties")
println("-"^60)

println("\nPhase space structure:")
println("  - Dimension: 4 (V, n, m, h)")
println("  - Stable fixed point (rest)")
println("  - Separatrix (threshold manifold)")
println("  - Limit cycle (repetitive firing)")
println()
println("Bifurcation behavior:")
println("  - I_ext < threshold: stable rest")
println("  - I_ext ≈ threshold: saddle-node bifurcation")
println("  - I_ext > threshold: limit cycle")

println("\n" * "-"^60)
println("6. Biological Significance")
println("-"^60)

println("\nNobel Prize 1963:")
println("  Awarded to Hodgkin & Huxley for:")
println("  - Explaining ionic basis of action potentials")
println("  - Quantitative modeling of excitable membranes")
println("  - Foundation of modern neuroscience")
println()
println("Impact:")
println("  - Understanding neural computation")
println("  - Drug development (ion channel blockers)")
println("  - Neural prosthetics and stimulation")
println("  - Cardiac pacemaker design")

println("\n" * "-"^60)
println("7. Numerical Considerations")
println("-"^60)

println("\nNumerical challenges:")
println("  - Stiff equations (multiple timescales)")
println("  - m dynamics very fast (~0.1 ms)")
println("  - h, n slower (~1-10 ms)")
println("  - Requires small time steps or stiff solvers")
println()
println("Recommended settings:")
println("  - dt ≤ 0.01 ms for explicit methods")
println("  - Adaptive step size preferred")
println("  - Use get_hh_initial_state() for consistency")

println("\n" * "="^60)
println("Analysis Complete")
println("="^60)
println("\nSummary:")
println("  - HH model describes neural action potentials")
println("  - Exhibits excitable dynamics (threshold behavior)")
println("  - 4D system with complex phase space")
println("  - Foundation of computational neuroscience")
println("  - Nobel Prize winning work (1963)")
println("\n" * "="^60)
